### ISSUE TITLE
Why is Zoetrope.framesForIndexes a [Int:Frame] instead of just a [Frame]?

### ISSUE THREAD

**Issue by andrewzboard** [JanGorman/Zoetrope#1]
I would use the Dictionary, as you did, if I had to assign the values in an arbitrary order. Yet they are sequentially assigned in Zoetrope.frames(imageSource:). That would suggest an array would be more efficient. Is it just personal preference?

**Comment by JanGorman** [comment]
I honestly can't remember – took a quick look. I agree that an array makes more sense

**Comment by andrewzboard** [comment]
Thanks for the prompt reply!

Good, then I wasn’t missing anything. Thank you so much for posting this clear and concise GIF-rendering class. I might prefer using it to FLAnimatedImage, or XAnimatedImage.

If I could run only on iOS 11 or higher, I could use more system services.

Andrew

**Comment by andrewzboard** [comment]
Hi Jan,

Thanks again for your correspondence yesterday.

I hope this isn’t too much of an inconvenience, but I have a question about the Zoetrope code. (I can frame this question because your code is so clear!) It seems to me that the refresh callbacks are very slow at the animation startup. It happens both on simulator and device. Do you have any idea why? I see it in the animation and I measure it as follows.

I add these logging lines to your code:

var lastRefresh = 0.0   // Added
@objc func displayDidRefresh(_ displayLink: CADisplayLink) {
    let now = Date.timeIntervalSinceReferenceDate   // Added
    print("frame \(currentFrameIndex) delta = \(now-lastRefresh); duration = \(displayLink.duration)”) // Added
    lastRefresh = now  // Added

I play a GIF whose delays are all 1/60 = 0.0166..., so they should just display once every refresh. What the log tells me is this:

// Meaningless delta first time through.
frame  0 delta = 552167395.096065;   duration = 0.016666667

// Startup jitters? Delta varies widely.
frame  1 delta = 0.0217660665512085; duration = 0.016666667
frame  2 delta = 0.0641059875488281; duration = 0.016666667
frame  3 delta = 0.100059986114502;  duration = 0.016666667

// From here delta is uniformly wrong, at approx 0.06 sec.
frame  4 delta = 0.0628589391708374; duration = 0.016666667
frame  5 delta = 0.0593420267105103; duration = 0.016666667
frame  6 delta = 0.0604649782180786; duration = 0.016666667
frame  7 delta = 0.0654630661010742; duration = 0.016666667
frame  8 delta = 0.0629899501800537; duration = 0.016666667
frame  9 delta = 0.0638020038604736; duration = 0.016666667
frame 10 delta = 0.0597530603408813; duration = 0.016666667
frame 11 delta = 0.0553510189056396; duration = 0.016666667
frame 12 delta = 0.053508996963501;  duration = 0.016666667
frame 13 delta = 0.0602849721908569; duration = 0.016666667
frame  0 delta = 0.0746840238571167; duration = 0.016666667
frame  1 delta = 0.0087279081344604; duration = 0.016666667

// After here, delta is consistently correct.
frame  2 delta = 0.0166560411453247; duration = 0.016666667
frame  3 delta = 0.0172410011291504; duration = 0.016666667
frame  4 delta = 0.0169349908828735; duration = 0.016666667
frame  5 delta = 0.0158059597015381; duration = 0.016666667

Best,
Andrew

**Comment by andrewzboard** [comment]
Oh man, all the formatting I did in Mail got lost in that last post. Sorry for the non-monospaced font. And I used coloring too. Furrfu!

Also, the slowdown persists if I convert the `frames` member from a `Dict` to an `Array`. Still, it looks like something is slow just the first time around the cycle, which made me think of caching issues. But the callbacks to `displayDidRefresh` shouldn't be _that_ irregular, should they?

**Comment by JanGorman** [comment]
Sorry, it was late already yesterday. I'll check that out later today but one suggestion to look into would be
```swift
@objc func displayDidRefresh(_ displayLink: CADisplayLink) {
  print(displayLink.timestamp)
  …
}
```

The `displayLink` that's passed to the function contains some additional helpful properties to look at: https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648422-targettimestamp

**Comment by andrewzboard** [comment]
Thank you Jan, I did look at the timestamp, it gave the same information as the absolute time — namely, that the callback delta was way over 1/60 of a second, like five times as large. But only at startup.

I hacked over it all day, and had it narrowed way down to a small bit of code that still exhibited the stutter, and was thinking of using an Apple Support Incident to get an explanation. But now I’m looking at solving my problem another way, not with animated GIFs.

It does seem strange that a displayLink would be so unreliable, so if you learn anything please let me know. Otherwise it will just remain a mystery. Until the next time I decide I need a DisplayLink instead of a Timer.

Andrew

**Comment by JanGorman** [comment]
So when I ran this, I get the following, without the startup jitters:
```
frame 0 delta = 552253651.17127; duration = 0.016675208333333334
frame 0 delta = 0.0006690025329589844; duration = 0.016675208333333334
frame 0 delta = 0.016077041625976562; duration = 0.016675208333333334
frame 1 delta = 0.016688942909240723; duration = 0.016675208333333334
frame 1 delta = 0.01667499542236328; duration = 0.016675208333333334
frame 2 delta = 0.016653060913085938; duration = 0.016675208333333334
frame 2 delta = 0.01668095588684082; duration = 0.016675208333333334
frame 2 delta = 0.016752958297729492; duration = 0.016675208333333334
frame 3 delta = 0.016700029373168945; duration = 0.016675208333333334
frame 3 delta = 0.016621947288513184; duration = 0.016675208333333334
frame 4 delta = 0.01668703556060791; duration = 0.016675208333333334
frame 4 delta = 0.016662001609802246; duration = 0.016675208333333334
frame 5 delta = 0.016674041748046875; duration = 0.016675208333333334
frame 5 delta = 0.016673922538757324; duration = 0.016675208333333334
frame 5 delta = 0.016677021980285645; duration = 0.016675208333333334
frame 6 delta = 0.01667499542236328; duration = 0.016675208333333334
frame 6 delta = 0.01667499542236328; duration = 0.016675208333333334
frame 7 delta = 0.01667499542236328; duration = 0.016675208333333334
frame 7 delta = 0.01673901081085205; duration = 0.016675208333333334
frame 7 delta = 0.016618013381958008; duration = 0.016675208333333334
frame 8 delta = 0.016640067100524902; duration = 0.016675208333333334
frame 8 delta = 0.016768932342529297; duration = 0.016675208333333334
frame 9 delta = 0.01669907569885254; duration = 0.016675208333333334
frame 9 delta = 0.01663196086883545; duration = 0.016675208333333334
frame 10 delta = 0.016744017601013184; duration = 0.016675208333333334
frame 10 delta = 0.016595005989074707; duration = 0.016675208333333334
frame 10 delta = 0.01673591136932373; duration = 0.016675208333333334
frame 11 delta = 0.01662003993988037; duration = 0.016675208333333334
frame 11 delta = 0.01668095588684082; duration = 0.016675208333333334
frame 12 delta = 0.016709089279174805; duration = 0.016675208333333334
frame 12 delta = 0.01663792133331299; duration = 0.016675208333333334
frame 12 delta = 0.016703009605407715; duration = 0.016675208333333334
frame 13 delta = 0.016637086868286133; duration = 0.016675208333333334
frame 13 delta = 0.016688942909240723; duration = 0.016675208333333334
frame 14 delta = 0.01672196388244629; duration = 0.016675208333333334
frame 14 delta = 0.016628026962280273; duration = 0.016675208333333334
frame 15 delta = 0.016739964485168457; duration = 0.016675208333333334
frame 15 delta = 0.016624093055725098; duration = 0.016675208333333334
frame 15 delta = 0.016737937927246094; duration = 0.016675208333333334
frame 16 delta = 0.01661098003387451; duration = 0.016675208333333334
frame 16 delta = 0.01664602756500244; duration = 0.016675208333333334
frame 17 delta = 0.01674199104309082; duration = 0.016675208333333334
frame 17 delta = 0.016613006591796875; duration = 0.016675208333333334
```

Running on an iPhone X though. If you're able to share the gif that you used for testing I'd be happy to run the tests with the same image too.

I also looked at instruments but didn't find anything. I was also thinking that the new `os_signpost` API ([Session 405 "Measuring Performance using Logging"](https://developer.apple.com/videos/play/wwdc2018/405/)) might be of use here but my other device with iOS 12 installed is at the office, alas…

**Comment by andrewzboard** [comment]
Hi Jan,

I sent a copy of the offending file, but it is too large (11MB) for email. That could be the problem in the first place: the images are fresh from the graphic artist, hi-res at 2000x2000. There are sixteen of them in the GIF.

I don’t have the facilities to extract the separate GIFs, resize and recombine them again, so the question may have to wait a while. But if you can create some dummy GIF file of that size and count, maybe it would make your machine stutter too.

Andrew

**Comment by JanGorman** [comment]
Hi,

Ok, such a gif will be huge in memory of course. The memory deep dive session in this year's WWDC covered such a case. There's always https://imageoptim.com/mac 😊

Out of curiosity I'll test your case with some random images later today.

**Comment by JanGorman** [comment]
Hi Andrew,

I was able to reproduce the same results with such a huge gif – the actual file size doesn't seem to matter. My test file was just solid colours (the gif itself being only 62kb). This is in line with what was mentioned in the WWDC session I mentioned in my previous comment. If it is an option you're likely to get better results with a video file instead of a gif.

**Comment by andrewzboard** [comment]
Thank you Jan, I am grateful for your generous help. I agree that a video file would save space — of course, that is what compression is all about. The challenge is that iOS doesn’t have much support for videos with transparency. The only solution I know is Mo DeJong’s library, which is good. But is a mass of Obj-C code that is a challenge (not impossible, I’ve done it) to integrate with Swift.

In any case I’m glad it’s not just my computer. 

Thanks again for your time, and your useful contribution on GitHub. It taught me exactly what I needed to know.

Andrew
