### ISSUE TITLE
Gifs are going faster

### ISSUE THREAD

**Issue by allaire** [JanGorman/Zoetrope#4]
Just updated Agrume, and I saw that you switched the Gif library, nice work. I just hit one problem, which is that the gifs now are going much faster.

Here's my code:

```
            guard var image = viewModel.originalImage ?? viewModel.image.value else { return }
            
            let isGIF = viewModel.originalImageUrl?.contains(".gif") ?? false
            
            if let imageData = viewModel.originalImageData, let imageFromData = UIImage(gifData: imageData), isGIF {
                image = imageFromData
            }
            
            let agrume = Agrume(image: image, background: .blurred(.dark))
            agrume.statusBarStyle = .lightContent
            agrume.show(from: topViewController)
```

Here's a side by side comparison: https://cl.ly/f31fc50f7f62

Attached the gifs:

![rotating_earth_ large](https://user-images.githubusercontent.com/304461/47178515-7364d100-d2e9-11e8-9248-98697749cea9.gif)
![giphy](https://user-images.githubusercontent.com/304461/47178516-7364d100-d2e9-11e8-8157-4d0ad8f0667c.gif)

**Comment by JanGorman** [comment]
Thanks for the report! This should not be the case of course. I will look into it

**Comment by JanGorman** [comment]
I reverted back to SwiftyGif – using the other lib was really just a stopgap measure because SwiftyGif was a bit slow in updating to Swift 4.2. I'll push the fresh release now
